apiVersion: v1
kind: Service
metadata:
  name: exercise-app
spec:
  selector:
    app: exercise-app
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise-app
  template:
    metadata:
      labels:
        app: exercise-app
    spec:
      containers:
      - name: exercise-app
        image: wyliebrown1990/exercise-app:1.0
        env:
        - name: DATABASE_URL
          value: "postgresql://wyliebrown:test123@postgres:5432/exercise"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "otel-collector:4317"
        ports:
        - containerPort: 5001
