services:
  app:
    image: wyliebrown1990/exercise-app:1.0
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: "postgresql://wyliebrown:test123@postgres:5432/exercise"
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
    depends_on:
      - postgres
      - otel-collector

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: wyliebrown
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: exercise
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/config.yaml:/etc/otel-collector-config.yaml  
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP

volumes:
  pgdata: