receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: "localhost:14250"  # Jaeger gRPC endpoint
    tls_enabled: false
  prometheus:
    endpoint: "0.0.0.0:9464"
  logging:
  otlphttp:
    endpoint: "https://157526203278.collect.observeinc.com/v2/otel"
    headers:
      authorization: "Bearer ds1rdQu4lbajALY7Pd1I:VgLZH4wBaqq611lfJwbF129-6KcTDX4R"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, otlphttp]
